[package]
name = "gs2compiler"
version = "0.2.3"
edition = "2021"
build = "build.rs"
description = "Compiles GS2 source code into GS2 bytecode."
license = "GPL-3.0-only"

[dependencies]
libc = "0.2.155"

[build-dependencies]
cmake = "0.1"